//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliotheque.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class auteur
    {
        public int Id { get; set; }
        [DisplayName("Nom Auteur")]
        [Required(ErrorMessage = "Le nom de l'auteur est requis", AllowEmptyStrings = false)]
        public string nom { get; set; }
        [DisplayName("Prénom Auteur")]
        [Required(ErrorMessage = "Le prénom de l'auteur est requis", AllowEmptyStrings = false)]
        public string prenom { get; set; }
        [DisplayName("Id Ouvrage")]
        [Required(ErrorMessage = "Id ouvrage est requis", AllowEmptyStrings = false)]
        public int idouvrage { get; set; }
    
        public virtual ouvrage ouvrage { get; set; }
    }
}
