//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliotheque.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class etudiant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public etudiant()
        {
            this.emprunt = new HashSet<emprunt>();
        }
    
        public int Id { get; set; }
        [DisplayName("Nom Etudiant")]
        [Required(ErrorMessage = "Nom Etudiant est requis", AllowEmptyStrings = false)]
        public string nom { get; set; }
        [DisplayName("Prénom Etudiant")]
        [Required(ErrorMessage = "Prénom Etudiant est requis", AllowEmptyStrings = false)]
        public string prenom { get; set; }
        [DisplayName("Niveau Etudiant")]
        [Required(ErrorMessage = "Niveau Etudiant est requis", AllowEmptyStrings = false)]
        public Niveau niveau { get; set; }
        public string login { get; set; }
    
        public virtual Compte Compte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emprunt> emprunt { get; set; }
    }
}
