//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliotheque.Models
{
    using System;
    
    public enum Niveau : int
    {
        L1 = 1,
        L2 = 2,
        L3 = 3,
        M1 = 4,
        M2 = 5,
        Doctora = 6
    }
}
