//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionBibliotheque.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ouvrage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ouvrage()
        {
            this.auteur = new HashSet<auteur>();
            this.emprunt = new HashSet<emprunt>();
        }
    
        public int Id { get; set; }
        [DisplayName("Titre Ouvrage")]
        [Required(ErrorMessage = "Titre Ouvrage est requis", AllowEmptyStrings = false)]
        public string titre { get; set; }        
        public System.DateTime edition { get; set; }
        [DisplayName("Nombre d'exemplaire de l'ouvrage")]
        [Required(ErrorMessage = "Nombre d'exemplaire de l'ouvrage est requis", AllowEmptyStrings = false)]
        public int nbExemplaires { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auteur> auteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emprunt> emprunt { get; set; }
    }
}
